### ISSUE TITLE
#Proposal migration to `jupyterlab-contrib` organization

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab-contrib/jupyterlab_spellchecker#42]
Hey @ijmbarr 

I created a new organization [jupyterlab-contrib](https://github.com/jupyterlab-contrib) to gather extensions highly used by the community to increase their visibility and to attract attention on volunteers to help maintain them. Some extensions have already been transferred like jupyter-archive or jupyterlab-kernelspy.

As you were in the past interested to transfer this extension to the community, I wonder if you would be interested in transferring it to that organization?

> The new organization is mirroring the jupyter_contrib_nbextensions repository. In particular it is not endorsed officially by the Jupyter board/developpers.

**Comment by krassowski** [comment]
Context:
- many jupyterlab team members appreciate your extension and would even consider moving it to @jupyterlab organization https://github.com/jupyterlab/team-compass/issues/85
- independently there was a discussion on where such extensions should live https://github.com/jupyterlab/team-compass/issues/52 and this lead @fcollonval to create @jupyterlab-contrib

I would be very happy to see this happen (to whichever of the two organizations). @fcollonval the target on the main organization was due to the languagepack discussion (dictionaries would become a part of the core infrastructure in a way), but I believe it is good to go to contrib as well.

**Comment by fcollonval** [comment]
Thanks for bringing more history information @krassowski

**Comment by ijmbarr** [comment]
Hi @fcollonval

My situation is that I no longer use jupyterlab as actively as I used to, and don't have time to actively develop this extension. I'm happy to handle PRs and releases for now, but am looking to hand it over.

What would transferring the extension to jupyterlab-contrib mean? It's not clear to me who would be responsible for maintaining it.

**Comment by fcollonval** [comment]
Thank you for reaching out @ijmbarr 

GitHub allows finer authorization/access control in organization than in personal spaces. This is the reason I created the jupyterlab-contrib organization to be able to easily manage maintainer/contributor roles. To answer more precisely your question.

> What would transferring the extension to jupyterlab-contrib mean?

The goal is to have multiple people with PR merge and publication rights (on GitHub but also on the NPM and Python packages) to ease maintenance by distributing the workload among the volunteers.

> It's not clear to me who would be responsible for maintaining it.

For now I'm the owner of the organization as well as the other extension authors. I'll initiate a discussion to determine a clear policy.

**Comment by ocordes** [comment]
Hi @ijmbarr and @fcollonval ,

I'm very interested in the future development of the jupyterlab_spellcheker, since I'm heavily using the jupyterlab for my work as a teacher and python tutor. Spellchecking is something we actually need to write good tutorials also in different languages. If I can do something useful for this project ...

Cheers,
   Oliver

**Comment by fcollonval** [comment]
Thanks for the proposal @ocordes 

For now only @ijmbarr has full rights on this project as it is part of is personal projects. If he agrees to migrate it to `jupyterlab-contrib`, the workflow will be the following:

1. I will invite @ijmbarr to join the `jupyterlab-contrib` organization
2. Upon invitation approval @ijmbarr will be able to transfer this project to `jupyterlab-contrib`
3. I can grant you advance rights on the project

By the rules of GitHub only @ijmbarr as the sole owner of this repository has the right to transfer it to another organization.

**Comment by ijmbarr** [comment]
Hi @fcollonval - I'm happy to begin the migration to `jupyterlab-contrib`.

**Comment by fcollonval** [comment]
Hey @ijmbarr awesome.

Could you please create a transfer issue to keep track of the process (here is the [link](https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/new?assignees=&labels=transfer&template=transfer-repository-to-this-organization.md&title=))?

In the meantime, you should have received an invitation to join the github and the npm organization.

**Comment by fcollonval** [comment]
Transfer is complete :tada: Thanks again @ijmbarr
